Resources:

    MyS3Bucket:
        Type: AWS::S3::Bucket
        DeletionPolicy: Delete
        Properties:
            BucketName: group06isludatalake

    MyS3Bucket1:
        Type: AWS::S3::Bucket
        DeletionPolicy: Delete
        Properties:
            BucketName: group06isluoutput
